"""Add QR code filename column to Student model

Revision ID: c754c1227c15
Revises: 282827c12bfa
Create Date: 2025-01-24 04:52:05.252231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c754c1227c15'
down_revision = '282827c12bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_filename', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('qr_code_filename')

    # ### end Alembic commands ###
